### ISSUE TITLE
Servlets in Jakarta EE projects always write metadata to web.xml instead of using annotations

### ISSUE THREAD

**Issue by nitind** [eclipse-jeetools/webtools.javaee#11]
3.34

Seems consistent that while Java EE projects work correctly, in a Jakarta EE (5+) project, the web.xml file is created and the servlet/filter/listener information is written there instead of into the new class.

For whether the annotations are added to the class, the version checks in org.eclipse.jst.j2ee.internal.web.operations.*Template seem to be the culprits. Why the operations insist on writing out the web.xml with that information is still a mystery.

**Comment by cypher256** [comment]
If web.xml doesn't exist then I don't think you need to write it out.
