### ISSUE TITLE
ArrayList conflict of duplicates

### ISSUE THREAD

**Issue by onesaif** [eclipse-jeetools/webtools.javaee#12]
Hello Team,

I am learning CoreJAVA and while I came across Collections such as 'List' interface with class ArrayList, I tried to use addAll from object 'b' to object 'a' in line number 16 and within object a, there are duplicate Strings. I queried for the indexOf the duplicate string from object 'a' in line number 18, and I got the output of '0'th Index, but in line number 20 I called the '2'nd index which has the the duplicate value. In this case line number 18 "System.out.println(a.indexOf("Saif"));" **doesn't print all the indexes which has the duplicate value 'Saif'** from the ArrayList 'a'. Please have a look.

```
package javaCore;
import java.util.ArrayList;
public class arrayList {
	public static void main(String[] args) {
		ArrayList<String> a = new ArrayList<String>();
		a.add("Saif");
		a.add("Uddin");
		a.add("Ahamed");
		System.out.println(a);
		a.add(1,"Jimmy");
		a.remove("Uddin");
		System.out.println(a);
		ArrayList<String> b = new ArrayList<String>();
		b.add("one");
		b.add("Saif");
		a.addAll(1, b);
		System.out.println(a);
		System.out.println(a.indexOf("Saif"));
		System.out.println(a.indexOf("Jimmy"));
		System.out.println(a.get(2));	
	}
}
```

Sincerely,
Saif

**Comment by nitind** [comment]
What does this issue have to do with this repository?

**Comment by onesaif** [comment]
I thought it is a forum to list any issues. If not, could you please guide me.

**Comment by nitind** [comment]
It is not. Issues areas of repositories on GitHub are for [tracking work and reporting problems](https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart).

For learning questions, you could use https://javaranch.com/ or https://stackoverflow.com/.
